#!/usr/bin/env python3
"""Render a rattler-build recipe for ONE shared side artifact.

Side artifacts -- nvshmem, the nvidia-* payload libs (libcudnn today) and the
PyPI wheel repacks (triton, cuda-bindings) -- are not extra outputs of the
torch recipe, deliberately:

  * each is repacked from a DIFFERENT upstream wheel than the torch recipe
    declares in `source:`. One recipe carries one verified source; folding
    these in would make that sha256 stop meaning "the verified source of this
    artifact", which is the property the whole migration was bought for.
  * they are SHARED across many torch cells and immutable at SIDE_BUILD. As
    outputs of the torch recipe every cell would rebuild them, and two cells
    would produce the same filename with different info/recipe contents --
    exactly the published-asset overwrite we must never do.
  * their build numbers move on a different schedule from the torch entries:
    one recipe cannot carry two immutability policies without confusing both.

Which side artifacts a cell needs is discovered during the torch surgery, so
render_recipe.py records them in meta.json as `side_requests`; this script
turns one such request into a recipe.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import torch_repack as tr  # noqa: E402  (path set above)


def wheel_tags(req: dict) -> list[str]:
    """The filename fragments that pick this request's wheel -- mirrors the
    tag list each builder passes to side_wheel()."""
    plat = "aarch64" if req["subdir"] == "linux-aarch64" else "x86_64"
    if req["kind"] == "pywheel":
        return [f"-cp{req['py'].replace('.', '')}-", plat]
    return [plat]


def render(req: dict, meta: dict, *, wheel_url: str, wheel_sha: str,
           tool_sha: str) -> str:
    index, about = meta["index"], meta["about"]
    pad = " " * 6

    def dep_list(deps: list[str], indent: int) -> str:
        p = " " * indent
        return "".join(f"\n{p}- {json.dumps(d)}" for d in deps) or " []"

    extra = dict(about.get("extra", {}))
    extra.update(tr.provenance())
    extra_yaml = "".join(f"\n{pad}{k}: {json.dumps(v)}"
                         for k, v in sorted(extra.items())) or " {}"
    lic_files = "".join(f"\n{pad}  - {json.dumps(n)}"
                        for n in sorted(meta["licenses"])) or " []"

    side_args = (f"--side-kind {req['kind']} --side-name {req['pypi_name']} "
                 f"--side-version {req['version']}")
    if req["kind"] == "nvidia-lib":
        side_args += f" --side-conda-name {req['conda_name']}"

    return f"""# GENERATED by tools/render_side_recipe.py -- do not edit.
# side artifact: {req['kind']} {req['pypi_name']} {req['version']} {req['subdir']}
package:
  name: {index['name']}
  version: {json.dumps(index['version'])}

source:
  # The upstream wheel, verified structurally. Side-repack sources always have
  # a published digest -- the PyPI API returns one for every file -- so unlike
  # some torch cells this is never a TOFU pin.
  url: {json.dumps(wheel_url)}
  sha256: {json.dumps(wheel_sha)}

build:
  number: {index['build_number']}
  string: {json.dumps(index['build'])}
  dynamic_linking:
    # The payload is NVIDIA's (or upstream's) own binaries. The surgery
    # already settled every RPATH and DT_NEEDED; anything else rewriting them
    # would break the audit that verify_repack.py enforces.
    binary_relocation: false
  script:
    content: |
      set -euo pipefail
      "$BUILD_PREFIX/bin/python" "$RECIPE_DIR/torch_repack.py" \\
        --version 0 --flavour {index['build'].split('_')[0]} --python {req.get('py', '3.12')} \\
        --subdir {req['subdir']} --side-build-number {index['build_number']} \\
        {side_args} --self-sha256 {tool_sha} \\
        --side-wheel "$SRC_DIR"/*.whl \\
        --stage-prefix "$PREFIX" --work "$SRC_DIR/_work"

requirements:
  build:
    - python {req.get('py', '3.12')}.*
    - zstandard
    - patchelf
  run:{dep_list(index.get('depends', []), 4)}
  run_constraints:{dep_list(index.get('constrains', []), 4)}

about:
  homepage: {json.dumps(about.get('home', ''))}
  license: {json.dumps(about.get('license', ''))}
  summary: {json.dumps(about.get('summary', ''))}
  license_file:{lic_files}

extra:{extra_yaml}
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--request", required=True,
                    help="one entry of meta.json's side_requests, as JSON")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--work", type=Path, required=True)
    ap.add_argument("--side-build-number", type=int, default=0)
    ap.add_argument("--check", action="store_true",
                    help="fail if the rendered recipe or its torch_repack.py "
                         "snapshot differs from a fresh render")
    args = ap.parse_args()

    req = json.loads(args.request)
    args.out.mkdir(parents=True, exist_ok=True)
    args.work.mkdir(parents=True, exist_ok=True)

    url, sha = tr.pypi_wheel_url(req["pypi_name"], req["version"],
                                 wheel_tags(req))

    # Run the real builder once to learn the metadata it computes (deps come
    # out of an ELF/METADATA audit, so they cannot be written by hand).
    meta_path = args.work / "side_meta.json"
    prefix = args.work / "prefix"
    if prefix.exists():
        shutil.rmtree(prefix)
    cmd = [sys.executable, str(HERE / "torch_repack.py"),
           "--version", "0", "--flavour", "cu12", "--python",
           req.get("py", "3.12"), "--subdir", req["subdir"],
           "--side-build-number", str(args.side_build_number),
           "--side-kind", req["kind"], "--side-name", req["pypi_name"],
           "--side-version", req["version"],
           "--stage-prefix", str(prefix), "--emit-metadata", str(meta_path),
           "--work", str(args.work / "surgery")]
    if req["kind"] == "nvidia-lib":
        cmd += ["--side-conda-name", req["conda_name"]]
    subprocess.run(cmd, check=True)

    meta = json.loads(meta_path.read_text())
    tool_src = (HERE / "torch_repack.py").read_bytes()
    # Same reason as the torch recipe: the recipe dir is outside
    # rattler-build's staging-cache key, so the script's hash rides in the
    # build command and the script re-checks it at run time.
    tool_sha = hashlib.sha256(tool_src).hexdigest()
    text = render(req, meta, wheel_url=url.split("#")[0], wheel_sha=sha,
                  tool_sha=tool_sha)

    if args.check:
        drift = []
        cur = args.out / "recipe.yaml"
        if not cur.is_file() or cur.read_text() != text:
            drift.append("recipe.yaml")
        snap = args.out / "torch_repack.py"
        if not snap.is_file() or snap.read_bytes() != tool_src:
            drift.append("torch_repack.py")
        if drift:
            sys.exit(f"render drift in {args.out}: {', '.join(drift)} "
                     f"differ(s) from a fresh render -- re-run "
                     f"render_side_recipe.py")
        tr.log(f"no render drift in {args.out}")
        return

    (args.out / "recipe.yaml").write_text(text)
    (args.out / "torch_repack.py").write_bytes(tool_src)
    for name in sorted(meta["licenses"]):
        src = prefix / "share" / "licenses" / meta["index"]["name"] / name
        if src.is_file():
            shutil.copyfile(src, args.out / name)
    tr.log(f"side recipe -> {args.out / 'recipe.yaml'}")


if __name__ == "__main__":
    main()
